services:

  fastapi-backend:
    container_name: fastapi-backend
    #    restart: on-failure
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres-fastapi
    networks:
      - backend-network

  postgres-fastapi:
    image: 'bitnami/postgresql:latest'
    container_name: postgres-fastapi
    networks:
      - backend-network
    restart: on-failure
    env_file:
      - postgres.env
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

networks:
  backend-network:

volumes:
  postgres_data:
