[project]
name = "fastapi-sqlalchemy-mixin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.14.1",
    "black>=25.1.0",
    "fastapi>=0.115.11",
    "sqlalchemy>=2.0.38",
]
